[advisories]
version = 2
yanked = "warn"
ignore = []

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
]

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
